### ISSUE TITLE
Schedule to time off VPN

### ISSUE THREAD

**Issue by vunguyendjv** [FuturraGroup/OpenVPNXor#1]
How can I schedule to time off VPN in background mode.

**Comment by sergey-zhuravel** [comment]
hello, it's not possible to do this from the client side, you can do it on your server.

**Comment by vunguyendjv** [comment]
> hello, it's not possible to do this from the client side, you can do it on your server.

Hi @sergey-zhuravel . Thank for your answer. Do you have document to do it on server? Can you send me it? 
Thank you so much.

**Comment by sergey-zhuravel** [comment]
> > hello, it's not possible to do this from the client side, you can do it on your server.
> 
> Hi @sergey-zhuravel . Thank for your answer. Do you have document to do it on server? Can you send me it? Thank you so much.

we don't have documentation for the servers. You'd better ask for help on the official site openvpn.net

**Comment by vunguyendjv** [comment]
> > > hello, it's not possible to do this from the client side, you can do it on your server.
> > 
> > 
> > Hi @sergey-zhuravel . Thank for your answer. Do you have document to do it on server? Can you send me it? Thank you so much.
> 
> we don't have documentation for the servers. You'd better ask for help on the official site openvpn.net

thank you so much
