### ISSUE TITLE
I faced with problem

### ISSUE THREAD

**Issue by EvelinaAlexey** [FuturraGroup/OpenVPNXor#11]
I have error Compiled module was created by a different version of the compiler '5.9.0.128.108'; rebuild 'OpenVPNXor' and try again: /Users/developer/Downloads/aaa/Pods/OpenVPNXor/OpenVPNXor.framework/Modules/OpenVPNXor.swiftmodule/arm64-apple-ios.swiftmodule and don't now how to solve it. Pls help me.

**Comment by sergey-zhuravel** [comment]
update Xcode to the latest version and install 1.8 version of OpenVPNXor

**Comment by EvelinaAlexey** [comment]
I have last version of Xcode and my swift version 5.10

**Comment by sergey-zhuravel** [comment]
I checked again, Xcode 15.4 and 1.8 version of OpenVPNXor work fine

**Comment by SharonYangDev** [comment]
I also have error Compiled module:
Cannot load module 'OpenVPNXor' built with SDK 'iphoneos17.0' when using SDK 'iphoneos17.5': /Users/SmartVPN/Pods/OpenVPNXor/OpenVPNXor.framework/Modules/OpenVPNXor.swiftmodule/arm64-apple-ios.swiftmodule

I use pod install only for OpenVPNXor 1.4 version
How to doing update to 1.8 version of OpenVPNXor?

**Comment by sergey-zhuravel** [comment]
The latest version at the moment is 2.1

`pod 'OpenVPNXor', '~> 2.1'`

**Comment by SharonYangDev** [comment]
Only OpenVPNXor 1.4 version can still be installed.

Case 1:
`pod 'OpenVPNXor'`
```
pod install
Analyzing dependencies
Downloading dependencies
Installing OpenVPNXor (1.4)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.
```
Case 2:
pod 'OpenVPNXor', '~> 2.1'
```
[!] CocoaPods could not find compatible versions for pod "OpenVPNXor":
  In Podfile:
    OpenVPNXor (~> 2.1)

Specs satisfying the `OpenVPNXor (~> 2.1)` dependency were found, but they required a higher minimum deployment target.
```

I also try to delete podfile.lock and pod folder then reinstall again.

**Comment by sergey-zhuravel** [comment]
> Specs satisfying the `OpenVPNXor (~> 2.1)` dependency were found, but they required a higher minimum deployment target.

minimum target should be iOS 13

**Comment by SharonYangDev** [comment]
> > Specs satisfying the `OpenVPNXor (~> 2.1)` dependency were found, but they required a higher minimum deployment target.
> 
> minimum target should be iOS 13

Thank you very much. 
After updating minimum target to platform :ios, '12.0'
Xcode 16.2 and 2.1 version of OpenVPNXor work fine.
