### ISSUE TITLE
It seems not be working with vpngate .ovpn files

### ISSUE THREAD

**Issue by tomassilny** [FuturraGroup/OpenVPNXor#13]
Hello,

I tried to connect to a VPN server using .ovpn files from [VPN Gate](https://www.vpngate.net/), but it seems not to be working well. I've tried multiple servers with no success. 

I was able to call configureVPN, and it created a new VPN connection in the settings:

![99510](https://github.com/user-attachments/assets/9dc688f3-7888-408c-8901-ba426a995a04)

However, it seems wrong as the server address doesn't look correct. Could you please check if it works on your side with VPN gate servers, or give me some advice on what I might be doing wrong? 

This is my code:
```
import SwiftUI
import OpenVPNXor

struct ContentView: View {
    @State private var showAlert = false
    @State private var alertMessage = ""

    var body: some View {
        VStack {
            Button("Click Me") {
                configureVPN()
            }
            .alert(isPresented: $showAlert) {
                Alert(title: Text("VPN Status"), message: Text(alertMessage), dismissButton: .default(Text("OK")))
            }
        }
        .padding()
    }

    private func configureVPN() {
        // Find the .ovpn file
        guard let path = Bundle.main.path(forResource: "vpngate_public-vpn-90.opengw.net_tcp_443 (2)", ofType: "ovpn") else {
            alertMessage = "Failed to find .ovpn file in bundle."
            showAlert = true
            return
        }

        do {
            OpenVPNManager.setup(openvpnPacketTunnelIdentifier: "com.deletethis.TestVPN.VPN", appGroupIdentifier: "group.com.deletethis.TestVPN")

            // Load the .ovpn file data
            let url = URL(fileURLWithPath: path)
            let data = try Data(contentsOf: url)

            // Configure the VPN
            OpenVPNManager.shared.configureVPN(openVPNConfiguration: data, login: "vpn", pass: "vpn") { success in
                DispatchQueue.main.async {
                    if success {
                        OpenVPNManager.shared.connectVPN { errorDescription in
                            if let errorDescription = errorDescription {
                                alertMessage = "Failed to connect VPN: \(errorDescription)"
                            } else {
                                alertMessage = "VPN connected successfully."
                            }
                            showAlert = true
                        }
                    } else {
                        alertMessage = "Failed to configure VPN."
                        showAlert = true
                    }
                }
            }
        } catch {
            alertMessage = "Failed to load .ovpn file: \(error)"
            showAlert = true
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}

```
The error message I get: `OpenVPNXor: error in starting tunnel `

Thank you!

**Comment by sergey-zhuravel** [comment]
I checked and it works for me. Perhaps the config was not correct or you configured the PacketTunnelProvider incorrectly. See [Usage](https://github.com/FuturraGroup/OpenVPNXor?tab=readme-ov-file#usage) section.

**Comment by tomassilny** [comment]
Thanks for your reply @sergey-zhuravel. do you know how to call setup using Objective-C?

**Comment by sergey-zhuravel** [comment]
In Objective-C everything is the same as in Swift, just a different syntax

**Comment by Heartkage** [comment]
I also have same issue using vpngate .ovpn files. I'm pretty sure there is nothing wrong with the .ovpn file because I was able to use the same file connecting to the server through `OpenVPN Connect` app.

I'm coding in Swift using Xcode 15.3 with OpenVPNXor version 1.6

I've setup and configureVPN completed with success, but my configuration in iPhone Setting -> VPN -> Server shows the same as @tomassilny provided in the screenshot: "ServerAddress"
When I try to connect, the status turned "connecting", then it disconnect immediately

Log was something like this
[VPNManager] Profile Saved!
[VPNManager] status change: disconnected
[VPNManager] Disconnected!
[VPNManager] status change: connecting
[VPNManager] status change: disconnected
[VPNManager] Disconnected!
