### ISSUE TITLE
Failed to save the new configuration: Error Domain=NEVPNErrorDomain Code=1 "Missing name" UserInfo={NSLocalizedDescription=Missing name

### ISSUE THREAD

**Issue by ramandeep-softradix** [FuturraGroup/OpenVPNXor#14]
Getting below error while saving the profile:
**error in saving to preferences: Missing name Error saving VPN profile.**
 

   let login = "test"
        let pass = "test"
        
        OpenVPNManager.shared.configureVPN(openVPNConfiguration: configurationFileData, login: login, pass: pass) { success in
            DispatchQueue.main.async {
                   if success {
                       print("VPN Profile saved successfully.")
                       self.vpnStatusLabel.text = "Profile Saved"
                   } else {
                       print("Error saving VPN profile.")
                       self.vpnStatusLabel.text = "Profile Save Failed"
                   }
               }
        }

**Comment by sergey-zhuravel** [comment]
set this property:
`OpenVPNManager.shared.appName = "test name"`
