### ISSUE TITLE
[Question] How to calculate connection time and total download/upload packets?

### ISSUE THREAD

**Issue by dphans** [FuturraGroup/OpenVPNXor#16]
I've implemented `OpenVPNXor`, it's simple and easy to use.
I've build the OpenVPN server for my company, and use this library to connect to own server.

I've setup the CoreData to store PacketTransmitted (timestamp, upload/download in bytes).
Currently, I can determine through `VpnManagerPacketTransmitted` delegate method, but when app move background, the delegate method doesn't work after about 10 minutes (I know this is cause from iOS system).

So I setup the delegate in extension (`PacketTunnelProvider`), in `connect` method, but when connect to VPN, it stop immediately.

So how can I catch the transfer packets or total bytes transfer in a session?
Thank you!

**Comment by sergey-zhuravel** [comment]
Hi, you can't do this on the client, because the app doesn't live long in the background. This can only be done on the server side.
