### ISSUE TITLE
Missing Name

### ISSUE THREAD

**Issue by hoang143** [FuturraGroup/OpenVPNXor#17]
Hi, please help me to solve problem.
i initialization completed and when i call configureVPN, it show Error: Failed to save the new configuration: Error Domain=NEVPNErrorDomain Code=1 "Missing name" UserInfo={NSLocalizedDescription=Missing name}

Here is my code, please help me, thank you so much:
//
//  ViewController.swift
//  KS_VPN
//
//  Created by Van Dinh Hoang on 16/10/24.
//

import UIKit
import OpenVPNXor
import Foundation
import NetworkExtension

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        let button = UIButton(type: .system)
        button.setTitle("Click Me", for: .normal)
        button.backgroundColor = .systemBlue
        button.setTitleColor(.white, for: .normal)
        button.frame = CGRect(x: 0, y: 0, width: 200, height: 50)
        button.center = view.center
        button.addTarget(self, action: #selector(buttonTapped), for: .touchUpInside)
        view.addSubview(button)
    }
    
    @objc func buttonTapped() {
        print("Button was tapped!")
        startConnect()
    }
    
    func startConnect() {
        print("start connect")
        let ovpnFileName = "vpngate_219.100.37.193_udp_1195"
            guard let configurationData = loadOVPNFile(named: ovpnFileName) else {
                print("Cannot get ovpn file.")
                return
            }
            
            let login = "vpn"
            let pass = "vpn"
            
            OpenVPNManager.shared.configureVPN(openVPNConfiguration: configurationData, login: login, pass: pass) { success in
                if success {
                    OpenVPNManager.shared.connectVPN { errorDescription in
                        if let error = errorDescription {
                            print("cannot connect VPN: \(error)")
                        } else {
                            print("connect success")
                        }
                    }
                } else {
                    print("error when configure vpn ")
                }
            }
    }
    
    
    func loadOVPNFile(named fileName: String) -> Data? {
        guard let filePath = Bundle.main.path(forResource: fileName, ofType: "ovpn") else {
            print("File not found")
            return nil
        }
        
        do {
            let content = try String(contentsOfFile: filePath, encoding: .utf8)
            return content.data(using: .utf8)
        } catch {
            print("fail to load file: \(error)")
            return nil
        }
    }

}

**Comment by dphans** [comment]
Seem to related to https://github.com/FuturraGroup/OpenVPNXor/issues/14

After initialized, assign your extension name by calling:

```swift
OpenVPNManager.shared.appName = "YOUR_DISPLAY_NAME"
```

**Comment by sergey-zhuravel** [comment]
CFBundleDisplayName - set this key in the info.plist file
