### ISSUE TITLE
Not able to install the pod

### ISSUE THREAD

**Issue by aditya141025** [FuturraGroup/OpenVPNXor#3]
While installing the pod I'm getting the following error. I have created the podfile like below:
# platform :ios, '9.0'
target 'PacketTunnelOpenVPN' do
  use_frameworks!
   pod 'OpenVPNXor'
end

target 'QuilrOpenVPNDemo' do
  use_frameworks!
  pod 'OpenVPNXor'
end

![Screenshot 2023-09-27 at 4 06 56 PM](https://github.com/FuturraGroup/OpenVPNXor/assets/141843545/17d5bfb5-3040-4870-9ea6-1e86cacc83cd).
Could you please help me. Thanks in advance.

**Comment by sergey-zhuravel** [comment]
The screenshot shows the error “Couldn’t connect to server”, that is, the problem is in your Internet, try via another Internet.
