### ISSUE TITLE
Not able to use the Library in Xcode 14.2 Projects Intel Chip based Mac

### ISSUE THREAD

**Issue by aditya141025** [FuturraGroup/OpenVPNXor#4]
Hi All,
After successfully adding the pod dependency on my intel based Mac with Xcode 14.2 and iOS 16.2,  I'm getting the error "**Compiled module was created by a different version of the compiler; rebuild 'OpenVPNXor' and try again**". For reference, I'm adding the screenshot :
![Screenshot 2023-09-27 at 8 34 22 PM](https://github.com/FuturraGroup/OpenVPNXor/assets/141843545/cdaeeb1d-70d3-4c6d-9e1c-99bc9bcd60a1).

Is this Library is written only for Xcode15 environment. 
Please help me. Thanks in advance.

**Comment by sergey-zhuravel** [comment]
yes you are right, this library only works on Xcode15, update your Xcode version

**Comment by aditya141025** [comment]
After upgrading the Xcode15, I'm still getting the issue when I'm trying to import the **OpenVPNXor** in my project. Please refer screenshot attached:

![WhatsApp Image 2023-09-28 at 15 07 13](https://github.com/FuturraGroup/OpenVPNXor/assets/141843545/870d2a9b-6f4e-4294-9cb1-2b5dca458f35).
Could you please tell, what is wrong with my setting. Thanks in advance.

**Comment by sergey-zhuravel** [comment]
you are trying to run a project on a simulator, run only on a real device

**Comment by aditya141025** [comment]
While trying with real device having iOS 16.2 and Xcode 15 I'm getting the below error: Please refer screenshot:
![WhatsApp Image 2023-09-28 at 15 53 31](https://github.com/FuturraGroup/OpenVPNXor/assets/141843545/ac172aac-6b40-4a1c-8b58-b85e89f10fca)
What does it mean. Thanks in adavnce.

**Comment by sergey-zhuravel** [comment]
try doing a Clean Build Folder, deleting the Pods folder and the Podfile.lock file. And after that install everything again.

**Comment by aditya141025** [comment]
Its not working after doing all the stuffs that you provided to me.
Could you please provide me iOS Demo(Demo project) integrating this Library. I'll be really thankful to you.

**Comment by aditya141025** [comment]
I'm able to compile the code by setting **ENABLE_USER_SCRIPT_SANDBOXING to NO in build settings of Target**. While implementing I just want to know how can I implement code under this line **Saving configuration of the profile in the Network Extension preferences of the .ovpn file.**. Please refer screenshot

![Screenshot 2023-09-28 at 6 16 09 PM](https://github.com/FuturraGroup/OpenVPNXor/assets/141843545/cfaae693-15d3-4b5a-aef9-0d52b38d785e)
Do I need to crete a seperate file or how to save configuration of the profile in the Network Extension preferences of the .ovpn file. Could you please explain little more. I'll be really thankfull. Thanks in advance.

**Comment by sergey-zhuravel** [comment]
you need to place the contents of the ".ovpn" config into a String, and then convert it to Data
`let configurationFileContent = configOpenVPN.data(using: .utf8, allowLossyConversion: true)`

**Comment by aditya141025** [comment]
Could you please explain more about contents of .**ovpn** config. How can we create a .**ovpn** config. and where to put this .ovpn config code in the project. I'll be really thankful to you.

**Comment by sergey-zhuravel** [comment]
You do not need to create it yourself, in order to get it, contact the person who set up your VPN servers.
