### ISSUE TITLE
Not able to save the configuration 

### ISSUE THREAD

**Issue by aditya141025** [FuturraGroup/OpenVPNXor#6]
I'm trying to make OpenVPN client using this library. I did the necessary set up as per the instruction given in to readme. But while saving the  configuration of OpenVPN file.

```
func saveOpenVPNConfigurations() {
    guard
        let configurationFileURL = Bundle.main.url(forResource: "profile", withExtension: "ovpn"),
        let configurationFileContent = try? Data(contentsOf: configurationFileURL)

    else {
        fatalError()
    }
    
    let login = "***********"
    let pass = "***************"
    
    OpenVPNManager.shared.configureVPN(openVPNConfiguration: configurationFileContent, login: login, pass: pass) { success in
        if success {
            print("Profile saved successfully")
            /// Profile saved successfully.
            connectVPN()
        } else {
            print("Error saving profile")
            /// Error saving profile. See the description of the error in the delegate method - `VpnManagerConnectionFailed`
        }
    }
}
```
But profile are not getting saved and getting the below error:

 **Failed to save the new configuration: Error Domain=NEVPNErrorDomain Code=1 "Missing name" UserInfo={NSLocalizedDescription=Missing name}
error in saving to preferences: Missing name**
 Could you please tell me whats wrong I have done. Thanks in advance

**Comment by sergey-zhuravel** [comment]
The project name is used to save the configuration. Specify a name in the project settings.
